# Generated by Django 3.2 on 2021-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movrotativo_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
