# Generated by Django 3.2 on 2021-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('nomesobrenome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('receber_noticas', models.BooleanField()),
            ],
        ),
    ]
