# Generated by Django 3.2 on 2021-05-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='receber_noticas',
            new_name='receber_noticias',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='nomesobrenome',
            new_name='sobrenome',
        ),
    ]
